# File: .github/workflows/workflow.yml

on: [push, create, pull_request]

name: CI/CD pipeline

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo Build Completed
        echo Test Completed
        
  deploy_test:
    needs: build_and_test
    if: github.event_name == 'create' && github.ref ==  'refs/tags/test'
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo ${{ github.ref }}

  deploy_staging:
    needs: build_and_test
    if:  github.ref ==  'refs/tags/stage'
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo ${{ github.ref }}

  deploy_prod:
    needs: build_and_test
    if: github.ref ==  'refs/tags/prod'
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo ${{ github.ref }}
