# File: .github/workflows/workflow.yml

on: 
  create

name: Branch or Tag creation should trigger this 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo $ { GITHUB_REF }
