# File: .github/workflows/workflow.yml

on: [push, create, pull_request]

name: Multipurpose pipeline

jobs:
  - job: build_and_test
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo Build Completed
        echo Test Completed
        
  - job: deploy_test
    dependsOn: build_and_test
    condition: eq(${{ github.ref }}, 'refs/tags/test')
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo ${{ github.ref }}

  - job: deploy_staging
    dependsOn: build_and_test
    condition: eq(${{ github.ref }}, 'refs/tags/stage')
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo ${{ github.ref }}

  - job: deploy_prod
    dependsOn: build_and_test
    condition: eq(${{ github.ref }}, 'refs/tags/prod')
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo ${{ github.ref }}
